export const lattes = [
    {
        drink: 'Apple Spice Latte',
        image: 'https://divascancook.com/wp-content/uploads/2013/11/IMG_2586_2.jpg',
        description: 'Espresso and steamed milk with apple, cinnamon, and nutmeg',
        calories:120,
        fat:"0g",
        cholesterol:"0mg",
        sodium:"10mg",
        carbohydrates:"3g",
        sugar:"0g",
        caffeine:"360mg",
        protein:"0g",
    },
    {
        drink: 'Pumpkin Spice Latte',
        image: 'https://www.inspiredtaste.net/wp-content/uploads/2011/11/Pumpkin-Spice-Latte-Recipe-1200.jpg',
        description: "Espresso and steamed milk with pumpkin, cinnamon, and nutmeg",
        calories:120,
        fat:"0g",
        cholesterol:"0mg",
        sodium:"10mg",
        carbohydrates:"3g",
        sugar:"0g",
        protein:"1g",
        caffeine:"360mg",
    },
    {
        drink: 'Hazelnut Latte',
        image: 'https://i2.wp.com/www.meatlessmakeovers.com/wp-content/uploads/2020/01/Vegan-Hazelnut-Spiked-Latte-9-scaled.jpg?fit=2560%2C1707&ssl=1',
        description: 'House-made hazelnut-praline-infused milk with espresso',
        calories:120,
        fat:"0g",
        cholesterol:"0mg",
        sodium:"10mg",
        carbohydrates:"3g",
        sugar:"0g",
        protein:"1g",
        caffeine:"360mg"
    },
    {
        drink: 'Honey Oatmilk Latte',
        image: 'http://www.howsweeteats.com/wp-content/uploads/2016/02/oatmeal-latte-I-howsweeteats.com-5.jpg',
        description: 'Oatmilk and signature espresso with a hint of honey',
        calories:120,
        fat:"0g",
        cholesterol:"0mg",
        sodium:"10mg",
        carbohydrates:"3g",
        sugar:"0g",
        protein:"1g",
        caffeine:"360mg"
    },
    {
        drink: 'Cinnamon Dolce',
        image: 'https://bakingmischief.com/wp-content/uploads/2021/11/cinnamon-dolce-latte-image-683x1024.jpg',
        description: 'Freshly steamed milk and cinnamon dolce with our classic espresso',
        calories:120,
        fat:"0g",
        cholesterol:"0mg",
        sodium:"10mg",
        carbohydrates:"3g",
        sugar:"0g",
        protein:"1g",
        caffeine:"360mg"
    },
    {
        drink: 'Blonde Vanilla',
        image: 'https://www.valyastasteofhome.com/wp-content/uploads/2017/02/IMG_3193.jpg',
        description: 'Light roasted espresso with steamed milk and vanilla',
        calories:120,
        fat:"0g",
        cholesterol:"0mg",
        sodium:"10mg",
        carbohydrates:"3g",
        sugar:"0g",
        protein:"1g",
        caffeine:"360mg"
    }
]